/usr/local/lib/apache-tomcat-9.0.0.M19/bin/catalina.sh run
Using CATALINA_BASE:   /home/lyh/.IntelliJIdea2017.1/system/tomcat/Unnamed_stockOnline
Using CATALINA_HOME:   /usr/local/lib/apache-tomcat-9.0.0.M19
Using CATALINA_TMPDIR: /usr/local/lib/apache-tomcat-9.0.0.M19/temp
Using JRE_HOME:        /usr/local/jdk1.8.0_11
Using CLASSPATH:       /usr/local/lib/apache-tomcat-9.0.0.M19/bin/bootstrap.jar:/usr/local/lib/apache-tomcat-9.0.0.M19/bin/tomcat-juli.jar
[2017-08-21 11:12:18,916] Artifact stockOnline:war exploded: Server is not connected. Deploy is not available.
Connected to the target VM, address: '127.0.0.1:41779', transport: 'socket'
21-Aug-2017 11:12:19.566 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/9.0.0.M19
21-Aug-2017 11:12:19.570 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Mar 27 2017 12:09:59 UTC
21-Aug-2017 11:12:19.570 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         9.0.0.0
21-Aug-2017 11:12:19.570 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
21-Aug-2017 11:12:19.570 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.8.0-53-generic
21-Aug-2017 11:12:19.570 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
21-Aug-2017 11:12:19.570 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/jdk1.8.0_11/jre
21-Aug-2017 11:12:19.570 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_11-b12
21-Aug-2017 11:12:19.571 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
21-Aug-2017 11:12:19.571 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/lyh/.IntelliJIdea2017.1/system/tomcat/Unnamed_stockOnline
21-Aug-2017 11:12:19.571 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/lib/apache-tomcat-9.0.0.M19
21-Aug-2017 11:12:19.571 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/home/lyh/.IntelliJIdea2017.1/system/tomcat/Unnamed_stockOnline/conf/logging.properties
21-Aug-2017 11:12:19.571 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
21-Aug-2017 11:12:19.571 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:41779,suspend=y,server=n
21-Aug-2017 11:12:19.571 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote=
21-Aug-2017 11:12:19.572 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=1099
21-Aug-2017 11:12:19.572 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
21-Aug-2017 11:12:19.572 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
21-Aug-2017 11:12:19.572 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.rmi.server.hostname=127.0.0.1
21-Aug-2017 11:12:19.572 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
21-Aug-2017 11:12:19.572 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
21-Aug-2017 11:12:19.572 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/home/lyh/.IntelliJIdea2017.1/system/tomcat/Unnamed_stockOnline
21-Aug-2017 11:12:19.572 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/lib/apache-tomcat-9.0.0.M19
21-Aug-2017 11:12:19.572 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/lib/apache-tomcat-9.0.0.M19/temp
21-Aug-2017 11:12:19.572 信息 [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/local/lib/idea-IU-171.4073.35/bin::/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
21-Aug-2017 11:12:19.712 信息 [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
21-Aug-2017 11:12:19.732 信息 [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
21-Aug-2017 11:12:19.743 信息 [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
21-Aug-2017 11:12:19.745 信息 [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
21-Aug-2017 11:12:19.745 信息 [main] org.apache.catalina.startup.Catalina.load Initialization processed in 564 ms
21-Aug-2017 11:12:19.808 信息 [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
21-Aug-2017 11:12:19.810 信息 [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/9.0.0.M19
21-Aug-2017 11:12:19.836 信息 [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
21-Aug-2017 11:12:19.860 信息 [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
21-Aug-2017 11:12:19.868 信息 [main] org.apache.catalina.startup.Catalina.start Server startup in 123 ms
Connected to server
[2017-08-21 11:12:20,032] Artifact stockOnline:war exploded: Artifact is being deployed, please wait...
[2017-08-21 11:12:20,086] Artifact stockOnline:war exploded: Error during artifact deployment. See server log for details.
21-Aug-2017 11:12:29.836 信息 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor /home/lyh/.IntelliJIdea2017.1/system/tomcat/Unnamed_stockOnline/conf/Catalina/localhost/stockOnline.xml
21-Aug-2017 11:12:31.104 信息 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
11:12:31.235 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.servlet.DispatcherServlet - Initializing servlet 'dispatcher'
11:12:31.254 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Adding [servletConfigInitParams] PropertySource with lowest search precedence
11:12:31.254 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Adding [servletContextInitParams] PropertySource with lowest search precedence
11:12:31.266 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Adding [jndiProperties] PropertySource with lowest search precedence
11:12:31.267 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Adding [systemProperties] PropertySource with lowest search precedence
11:12:31.267 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Adding [systemEnvironment] PropertySource with lowest search precedence
11:12:31.267 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Initialized StandardServletEnvironment with PropertySources [servletConfigInitParams,servletContextInitParams,jndiProperties,systemProperties,systemEnvironment]
11:12:31.268 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] INFO org.springframework.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcher': initialization started
11:12:31.281 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Adding [servletConfigInitParams] PropertySource with lowest search precedence
11:12:31.281 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Adding [servletContextInitParams] PropertySource with lowest search precedence
11:12:31.281 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Adding [jndiProperties] PropertySource with lowest search precedence
11:12:31.281 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Adding [systemProperties] PropertySource with lowest search precedence
11:12:31.281 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Adding [systemEnvironment] PropertySource with lowest search precedence
11:12:31.281 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Initialized StandardServletEnvironment with PropertySources [servletConfigInitParams,servletContextInitParams,jndiProperties,systemProperties,systemEnvironment]
11:12:31.281 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Replacing [servletContextInitParams] PropertySource with [servletContextInitParams]
11:12:31.282 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.StandardServletEnvironment - Replacing [servletConfigInitParams] PropertySource with [servletConfigInitParams]
11:12:31.282 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] INFO org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Refreshing WebApplicationContext for namespace 'dispatcher-servlet': startup date [Mon Aug 21 11:12:31 CST 2017]; root of context hierarchy
11:12:31.328 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
11:12:31.330 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] INFO org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Registering annotated classes: [class com.config.MyMvcConfig]
11:12:31.353 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Bean factory for WebApplicationContext for namespace 'dispatcher-servlet': org.springframework.beans.factory.support.DefaultListableBeanFactory@3b40bb11: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,myMvcConfig]; root of factory hierarchy
11:12:31.364 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Registering scope 'request' with implementation [org.springframework.web.context.request.RequestScope@352a52f5]
11:12:31.364 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Registering scope 'session' with implementation [org.springframework.web.context.request.SessionScope@7da0206f]
11:12:31.364 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Registering scope 'globalSession' with implementation [org.springframework.web.context.request.SessionScope@637afe1d]
11:12:31.365 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Registering scope 'application' with implementation [org.springframework.web.context.support.ServletContextScope@5160bff1]
11:12:31.368 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
11:12:31.368 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
11:12:31.374 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor' to allow for resolving potential circular references
11:12:31.375 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
11:12:31.388 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
11:12:31.391 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.core.io.support.PathMatchingResourcePatternResolver - Resolved classpath location [com/stockonline/controller/] to resources [URL [file:/home/lyh/stockOnline/out/artifacts/stockOnline_war_exploded/WEB-INF/classes/com/stockonline/controller/]]
11:12:31.391 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.core.io.support.PathMatchingResourcePatternResolver - Looking for matching resources in directory tree [/home/lyh/stockOnline/out/artifacts/stockOnline_war_exploded/WEB-INF/classes/com/stockonline/controller]
11:12:31.391 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.core.io.support.PathMatchingResourcePatternResolver - Searching directory [/home/lyh/stockOnline/out/artifacts/stockOnline_war_exploded/WEB-INF/classes/com/stockonline/controller] for files matching pattern [/home/lyh/stockOnline/out/artifacts/stockOnline_war_exploded/WEB-INF/classes/com/stockonline/controller/**/*.class]
11:12:31.393 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.core.io.support.PathMatchingResourcePatternResolver - Resolved location pattern [classpath*:com/stockonline/controller/**/*.class] to resources [file [/home/lyh/stockOnline/out/artifacts/stockOnline_war_exploded/WEB-INF/classes/com/stockonline/controller/CityRestController.class], file [/home/lyh/stockOnline/out/artifacts/stockOnline_war_exploded/WEB-INF/classes/com/stockonline/controller/UserController.class]]
11:12:31.408 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - Identified candidate component class: file [/home/lyh/stockOnline/out/artifacts/stockOnline_war_exploded/WEB-INF/classes/com/stockonline/controller/CityRestController.class]
11:12:31.408 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - Identified candidate component class: file [/home/lyh/stockOnline/out/artifacts/stockOnline_war_exploded/WEB-INF/classes/com/stockonline/controller/UserController.class]
11:12:31.446 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registered bean definition for imported class 'org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration'
11:12:31.447 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.requestMappingHandlerMapping()
11:12:31.447 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.mvcPathMatcher()
11:12:31.448 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.mvcUrlPathHelper()
11:12:31.448 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.mvcContentNegotiationManager()
11:12:31.448 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.viewControllerHandlerMapping()
11:12:31.449 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.beanNameHandlerMapping()
11:12:31.449 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.resourceHandlerMapping()
11:12:31.449 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.mvcResourceUrlProvider()
11:12:31.450 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.defaultServletHandlerMapping()
11:12:31.450 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.requestMappingHandlerAdapter()
11:12:31.450 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.mvcConversionService()
11:12:31.450 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.mvcValidator()
11:12:31.451 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.mvcUriComponentsContributor()
11:12:31.451 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.httpRequestHandlerAdapter()
11:12:31.451 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.simpleControllerHandlerAdapter()
11:12:31.452 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.handlerExceptionResolver()
11:12:31.453 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.mvcViewResolver()
11:12:31.453 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registered bean definition for imported class 'org.springframework.scheduling.annotation.SchedulingConfiguration'
11:12:31.454 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.scheduling.annotation.SchedulingConfiguration.org.springframework.context.annotation.internalScheduledAnnotationProcessor()
11:12:31.454 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.config.MyMvcConfig.viewResolver()
11:12:31.454 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.config.MyMvcConfig.multipartResolver()
11:12:31.581 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassEnhancer - Successfully enhanced com.config.MyMvcConfig; enhanced class name is: com.config.MyMvcConfig$$EnhancerBySpringCGLIB$$4bbf6351
11:12:31.582 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassPostProcessor - Replacing bean definition 'myMvcConfig' existing class 'com.config.MyMvcConfig' with enhanced class 'com.config.MyMvcConfig$$EnhancerBySpringCGLIB$$4bbf6351'
11:12:31.598 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassEnhancer - Successfully enhanced org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration; enhanced class name is: org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration$$EnhancerBySpringCGLIB$$66b8fbd1
11:12:31.598 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassPostProcessor - Replacing bean definition 'org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration' existing class 'org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration' with enhanced class 'org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration$$EnhancerBySpringCGLIB$$66b8fbd1'
11:12:31.601 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassEnhancer - Successfully enhanced org.springframework.scheduling.annotation.SchedulingConfiguration; enhanced class name is: org.springframework.scheduling.annotation.SchedulingConfiguration$$EnhancerBySpringCGLIB$$4346cd16
11:12:31.601 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.context.annotation.ConfigurationClassPostProcessor - Replacing bean definition 'org.springframework.scheduling.annotation.SchedulingConfiguration' existing class 'org.springframework.scheduling.annotation.SchedulingConfiguration' with enhanced class 'org.springframework.scheduling.annotation.SchedulingConfiguration$$EnhancerBySpringCGLIB$$4346cd16'
11:12:31.605 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor'
11:12:31.605 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor'
11:12:31.606 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor' to allow for resolving potential circular references
11:12:31.629 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor'
11:12:31.630 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalRequiredAnnotationProcessor'
11:12:31.630 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.internalRequiredAnnotationProcessor'
11:12:31.630 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.internalRequiredAnnotationProcessor' to allow for resolving potential circular references
11:12:31.636 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.internalRequiredAnnotationProcessor'
11:12:31.636 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor'
11:12:31.636 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor'
11:12:31.638 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor' to allow for resolving potential circular references
11:12:31.652 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor'
11:12:31.652 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalScheduledAnnotationProcessor'
11:12:31.652 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.internalScheduledAnnotationProcessor'
11:12:31.654 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.scheduling.annotation.SchedulingConfiguration'
11:12:31.654 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.scheduling.annotation.SchedulingConfiguration'
11:12:31.659 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.scheduling.annotation.SchedulingConfiguration' to allow for resolving potential circular references
11:12:31.665 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.scheduling.annotation.SchedulingConfiguration'
11:12:31.685 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.internalScheduledAnnotationProcessor' to allow for resolving potential circular references
11:12:31.699 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.internalScheduledAnnotationProcessor'
11:12:31.701 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Unable to locate MessageSource with name 'messageSource': using default [org.springframework.context.support.DelegatingMessageSource@22bf25aa]
11:12:31.703 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Unable to locate ApplicationEventMulticaster with name 'applicationEventMulticaster': using default [org.springframework.context.event.SimpleApplicationEventMulticaster@5584b6ac]
11:12:31.704 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.ui.context.support.UiApplicationContextUtils - Unable to locate ThemeSource with name 'themeSource': using default [org.springframework.ui.context.support.ResourceBundleThemeSource@2c2e244f]
11:12:31.707 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@3b40bb11: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,myMvcConfig,cityRestController,userController,org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration,requestMappingHandlerMapping,mvcPathMatcher,mvcUrlPathHelper,mvcContentNegotiationManager,viewControllerHandlerMapping,beanNameHandlerMapping,resourceHandlerMapping,mvcResourceUrlProvider,defaultServletHandlerMapping,requestMappingHandlerAdapter,mvcConversionService,mvcValidator,mvcUriComponentsContributor,httpRequestHandlerAdapter,simpleControllerHandlerAdapter,handlerExceptionResolver,mvcViewResolver,org.springframework.scheduling.annotation.SchedulingConfiguration,org.springframework.context.annotation.internalScheduledAnnotationProcessor,viewResolver,multipartResolver]; root of factory hierarchy
11:12:31.707 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
11:12:31.707 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor'
11:12:31.707 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.context.annotation.internalRequiredAnnotationProcessor'
11:12:31.707 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor'
11:12:31.707 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.event.internalEventListenerProcessor'
11:12:31.707 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.event.internalEventListenerProcessor'
11:12:31.709 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.event.internalEventListenerProcessor' to allow for resolving potential circular references
11:12:31.716 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.event.internalEventListenerProcessor'
11:12:31.716 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.event.internalEventListenerFactory'
11:12:31.716 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.event.internalEventListenerFactory'
11:12:31.716 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.event.internalEventListenerFactory' to allow for resolving potential circular references
11:12:31.722 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.event.internalEventListenerFactory'
11:12:31.722 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'myMvcConfig'
11:12:31.722 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'myMvcConfig'
11:12:31.723 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'myMvcConfig' to allow for resolving potential circular references
11:12:31.733 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'myMvcConfig'
11:12:31.733 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'cityRestController'
11:12:31.733 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'cityRestController'
11:12:31.736 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.annotation.InjectionMetadata - Registered injected element on class [com.stockonline.controller.CityRestController]: AutowiredFieldElement for private com.stockonline.util.QueryStockByCode com.stockonline.controller.CityRestController.queryStockByCode
11:12:31.737 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'cityRestController' to allow for resolving potential circular references
11:12:31.739 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.annotation.InjectionMetadata - Processing injected element of bean 'cityRestController': AutowiredFieldElement for private com.stockonline.util.QueryStockByCode com.stockonline.controller.CityRestController.queryStockByCode
11:12:31.743 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] WARN org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cityRestController': Unsatisfied dependency expressed through field 'queryStockByCode'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.stockonline.util.QueryStockByCode' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
11:12:31.743 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@3b40bb11: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,myMvcConfig,cityRestController,userController,org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration,requestMappingHandlerMapping,mvcPathMatcher,mvcUrlPathHelper,mvcContentNegotiationManager,viewControllerHandlerMapping,beanNameHandlerMapping,resourceHandlerMapping,mvcResourceUrlProvider,defaultServletHandlerMapping,requestMappingHandlerAdapter,mvcConversionService,mvcValidator,mvcUriComponentsContributor,httpRequestHandlerAdapter,simpleControllerHandlerAdapter,handlerExceptionResolver,mvcViewResolver,org.springframework.scheduling.annotation.SchedulingConfiguration,org.springframework.context.annotation.internalScheduledAnnotationProcessor,viewResolver,multipartResolver]; root of factory hierarchy
11:12:31.743 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] DEBUG org.springframework.beans.factory.support.DisposableBeanAdapter - Invoking destroy() on bean with name 'org.springframework.context.annotation.internalScheduledAnnotationProcessor'
11:12:31.745 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] ERROR org.springframework.web.servlet.DispatcherServlet - Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cityRestController': Unsatisfied dependency expressed through field 'queryStockByCode'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.stockonline.util.QueryStockByCode' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:540)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:138)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:992)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4921)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5231)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:596)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1805)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:506)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:405)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1595)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:280)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1184)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1380)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.stockonline.util.QueryStockByCode' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1486)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	... 41 common frames omitted
21-Aug-2017 11:12:31.756 信息 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor /home/lyh/.IntelliJIdea2017.1/system/tomcat/Unnamed_stockOnline/conf/Catalina/localhost/stockOnline.xml has finished in 1,920 ms
21-Aug-2017 11:12:31.757 信息 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/lib/apache-tomcat-9.0.0.M19/webapps/manager
21-Aug-2017 11:12:31.775 信息 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/lib/apache-tomcat-9.0.0.M19/webapps/manager has finished in 18 ms
